### PR TITLE
Spell-test scripts in bin/

### PR DESCRIPTION
**Pull request by rwstauner**
my script had all the same errors as the module but i didn't notice...
i didn't realize it wasn't being tested ;-)

Specifying "bin" in the test doesn't seem to cause any problems if the directory doesn't exist.

If it becomes an issue in the future it could obviously be made configurable...
could even do something fancy like using `$zilla->plugin_named('ExecDir')->dir` I suppose.

### CODE REVIEW

**Comment by xenoterracide** [comment]
I wanted to say I'm going to accept this, (or fix it if I find a problem) but I want to get a couple of other things fixed before another release so I'm not sure on the timeframe.

**Comment by rwstauner** [comment]
cool, thanks.

**Comment by xenoterracide** [comment]
Is there any chance you'd be willing to write a test for this? to ensure the behavior works as intended, and continues to work in the future... adding tests to this distribution is one of the things I _need_ to do

**Comment by rwstauner** [comment]
I usually do include tests, but since this dist didn't have any (many dz
plugins don't), I didn't bother.

I'm sure I could come up with something.

I'll look at it later in the week.

**Comment by rwstauner** [comment]
On an unrelated note, while I do think it is appropriate for this plugin to automatically add author/copyright holder stopwords,
note that Pod::Weaver::Plugin::StopWords also does this (just in case you didn't know of the plugin and might want to use it).

**Comment by rwstauner** [comment]
In fact I think that was the original reason I wrote that plugin, but it does do a few other things.

**Comment by xenoterracide** [comment]
I apologize for taking so long to get this merged, personal life got all hectic for a few weeks, and I just moved to a new city. These were added to 2.1.0

**Pull request merged**
