### PR TITLE
Rewrite plugin to _not_ be a FileMunger

### PR DESCRIPTION
**Pull request by autarch**
This fixes a bug where it expected to see a file named xt/author/pod-spell.t
but recent versions of dzil seem to expose this as t/author-pod-spell.t

I wasn't able to come up with a test for this but I did test this with one of
my distros and it fixed the problem I was seeing.

Honestly, I have no idea what exactly changed. Regardless, this is more correct anyway. It's kind of silly to loop through _all_ the files in the distro just to find the one we want to munge. We might as well munge the content _before_ adding it to the list of files in the distro.

### CODE REVIEW

**Comment by autarch** [comment]
Hmm, now I'm wondering if this removes the change you added in 2.006003. That said, I can't tell since you didn't add a test for this. Not that I should point fingers given the lack of tests in this PR.

**Comment by autarch** [comment]
It'd probably be simpler to just revert to the 2.006002 code. I'm not sure my implementation is any better.

**Comment by karenetheridge** [comment]
No, the entire point of the previous change was to _not_ munge the file at file-gathering time -- that's too soon to call $zilla->distmeta and expect other plugins to have all metadata prepared.

"recent versions of dzil seem to expose this as t/author-pod-spell.t" -- no, this is you, using [ExtraTests] to rename the file, which is happening (because of your plugin ordering) before the template content is filled in.  If I recall, xeno did provide a warning about this in the documentation.

However, we can solve this a bit better by looking for the underlying file object (or caching it in the plugin), so we can still find it even if something else has come along and changed its name.  I'll work on that tonight.

**Comment by xenoterracide** [comment]
as a side note, I updated the docs for that issue... @karenetheridge anyway you could also come up with a test. I'll be honest I don't actually understand the issue you're solving here, I'm generally taking your word on there being some actual problem. But the pain with ExtraTests...

**Comment by autarch** [comment]
I'll close this since it sounds like there's a different way to address this.

**Comment by karenetheridge** [comment]
Fixed in either of:
https://github.com/xenoterracide/Dist-Zilla-Plugin-Test-PodSpelling/pull/23
https://github.com/xenoterracide/Dist-Zilla-Plugin-Test-PodSpelling/pull/24

**Pull request closed without merging**
