### PR TITLE
Topic/find moved file

### PR DESCRIPTION
**Pull request by karenetheridge**
One solution to #22: save the file object as it is added, so it can be munged later, even if it is renamed

I also fixed the test that does not run except under "dzil test", and added a test to ensure the file does not get munged until filemunging time.

### CODE REVIEW

**Comment by autarch** [comment]
FWIW, I think this is the best fix.

**Comment by xenoterracide** [comment]
but the build failed

**Comment by xenoterracide** [comment]
@karenetheridge ahem^ failing @autarch because there was some confusion over "branch naming and description" at the top of the pull request... (they were swapped, this contained the description for warning). Is this actually the version you want?

**Comment by autarch** [comment]
Yes, this branch doesn't require anyone to reorder their dist.ini file, which I think is the best solution.

**Pull request merged**
