### PR TITLE
add stopwords for contributors

### PR DESCRIPTION
**Pull request by garu**
Hi there! First of all, thanks for such a nice module :)

This patch adds stopwords for all the contributors listed under x_contributors on the META file. I stumbled on this while trying to use your plugin together with the ContributorsFromGit one, which automatically adds contributors to the dist.

Thanks!

### CODE REVIEW

**Comment by dagolden** [comment]
I would _love_ to see this applied and released.

**Comment by xenoterracide** [comment]
seems like a good idea, could we get a  test for it? should be as simple as adding a few lines to one of the existing tests.

**Comment by xenoterracide** [comment]
```
Can't use an undefined value as an ARRAY reference at /home/xenoterracide/projects/Dist-Zilla-Plugin-Test-PodSpelling/lib/Dist/Zilla/Plugin/Test/PodSpelling.pm line 77.
```

This patch causes the distribution to fail to run `dzil test` please fix and add write a unit test

**Comment by dagolden** [comment]
I have written a test and fixed the bugs, but other things are failing under prove.  I'm installing the author deps to try under dzil test.

**Pull request merged**
