### PR TITLE
Bump Test::Spelling prereq to 0.17 for windows fix

### LINKED ISSUE #7: checked.t hangs on Windows
Nothing is printed.
Strawberry 5.14.0, 5.8.9.

### PR DESCRIPTION
**Pull request by rwstauner**
closes gh-7.

Not sure if this is the branch you want, but you can cherry pick it or whatever

### CODE REVIEW

**Comment by xenoterracide** [comment]
https://rt.cpan.org/Public/Bug/Display.html?id=83328 0.16 and 0.17 break unicode support. I won't raise the requirements level until that's fixed.

**Comment by rwstauner** [comment]
Oh yeah I guess I forgot about that part...
probably because I can't imagine what it was about 0.16 that **broke** unicode support
(as far as I can tell there never was any support).

Maybe sartak/test-spelling#3 will get merged and that will be the end of it.

**Comment by xenoterracide** [comment]
maybe somebody changed a regex... or maybe it only broke against certain versions. I didn't bother to delve after I fixed the unicode bugs with this. But yeah once that's released, we can cut  a release with this fix, well.. probably have to bump the version 0.18 or whatever.

**Comment by rwstauner** [comment]
from what i can tell the only change was the Pod::Spell object is only instantiated once and reused... but I looked through the Pod::Spell code (and maybe even Pod::Parser) and I couldn't determine why that would cause an issue.

I did notice one other thing though, that the file path seemed to be always unix style in newer versions,
so at least that was a valuable fix.  Then yeah, hopefully bump to 0.18 and be done with it all.

**Pull request merged**
